GET http://localhost:5000/books/

###

GET http://localhost:5000/books/4/

###

POST http://localhost:5000/books/
Content-Type: application/json

{
    "bookname": "heart of the beat",
    "authorId": 104,
    "bookdetails": "hello siva",
    "bookId": 4
}

###

DELETE http://localhost:5000/books/4/

###

GET http://localhost:5000/authors/100/books/1/

###

PUT http://localhost:5000/books/4/
Content-Type: application/json

{
    "bookname": "hearts of the beat",
    "authorId": 104,
    "bookdetails": "hell ram",
    "bookId": 4
}